name: workiom_technical_test
description: "A technical test app for workiom."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  colorful_print: ^0.1.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  derry: ^1.5.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_timezone: ^5.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.3
  fluttertoast: ^9.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.1.1
  google_fonts: ^6.3.2
  injectable: ^2.7.0
  internet_connection_checker_plus: ^2.9.1
  json_annotation: ^4.9.0
  logger: ^2.6.2
  go_router: ^17.0.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2

scripts: derry.yaml

flutter:
  uses-material-design: true


  assets:
    - assets/svg/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500